import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Line } from "react-chartjs-2";
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
} from "chart.js";

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend
);

const priceData = [100,230,320,450,1200];
const timeStamp = ["JAN", "FEB", "MAR", "APR", "MAY"];
const data = {
  labels: timeStamp,
  datasets: [
    {
      label: "Revenue (USD) YTD (In hundred thousands)",
      fill: false,
      data: priceData,
      backgroundColor: "#0071bd",
      borderColor: "#0071bd",
    },
  ],
};

const options = {
  scales: {
    yAxes: [
      {
        ticks: {
          beginAtZero: true,
        },
      },
    ],
  },
};

const Dashboard: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {/* Welcome to <a href="https://nextjs.org">Next.js!</a> */}
          Welcome back, Jollibee #517
        </h1>

        <p className={styles.description}>
          It is currently {new Date().toString()}
        </p>

        <Line data={data} options={options} />
      </main>
    </div>
  );
};

export default Dashboard;
